---
- name: install ansible docker bindings
  import_tasks: ansible-docker.yml

- name: remove stale docker container (optional, so ok to fail)
  docker_container:
    name: mtproxy
    state: absent
  failed_when: false
  no_log: "{{ hide_secrets |bool }}"
...
