---
- name: remove stale docker container
  include_tasks: rmdocker.yml
  when: mtproxy_rmdocker |bool and lin_use_docker |bool
  tags: srv_mtproxy_rmdocker

- name: create group for proxy processes
  group:
    name: proxy
    gid: 13


- name: detect latest mtg release
  github_release:
    repository: 9seconds/mtg
    release: "{{ mtproxy_release }}"
    template: '{download_url}/mtg-{ver}-linux-{goarch}.tar.gz'
    creates: "{{ mtproxy_bin_file }}"
    reinstall: "{{ mtproxy_upgrade |bool }}"
    strip_v: true
  register: latest_mtg_release
  tags: srv_mtproxy_install

- name: download and unarchive mtproxy tarball
  unarchive:
    remote_src: true
    src: "{{ latest_mtg_release.url }}"
    dest: "{{ mtproxy_bin_file |dirname }}"
    extra_opts: --strip-components=1
    exclude:
      - LICENSE
      - README.md
      - SECURITY.md
    owner: root
    group: root
    mode: 0755
  when: latest_mtg_release is changed
  tags: srv_mtproxy_install


- name: configure mtproxy service
  template:
    src: mtproxy.toml
    dest: /etc/mtproxy.toml
    owner: root
    group: proxy
    mode: 0640
  notify: restart mtproxy service
  tags: srv_mtproxy_service

- name: setup mtproxy service unit
  template:
    src: mtproxy.service
    dest: /etc/systemd/system/mtproxy.service
    mode: 0644
  notify: restart mtproxy service
  tags: srv_mtproxy_service

- name: start mtproxy system service
  systemd:
    name: mtproxy
    state: started
    enabled: true
    daemon_reload: true
  tags: srv_mtproxy_service


- name: open (or block) mtproxy port in ufw
  ufw:
    port: "{{ mtproxy_port |string }}"
    rule: "{{ mtproxy_direct |bool |ternary('allow','deny') }}"
  no_log: "{{ hide_secrets |bool }}"
  when: lin_firewall == 'ufw'
  tags:
    - srv_mtproxy_firewall

- name: open (or block) mtproxy port in ferm
  ferm_port:
    port: "{{ mtproxy_port }}"
    zone: "{{ mtproxy_direct |bool |ternary('external','internal') }}"
    solo_zone: true
    comment: mtproxy
  when: lin_firewall == 'ferm'
  tags:
    - skip_ansible_lint
    - srv_mtproxy_firewall
...
